require("config.options")
require("config.lazy")
require("config.angular")
require("config.debug")
require("config.tree-sitter")
require('config.luasnip')

vim.keymap.set('n', '<leader>so', function ()
    vim.cmd('source $MYVIMRC')
    print('Resourced vimrc')
end, { desc = 'Source vimrc' })
